image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler jekyll
  - gem install jekyll-paginate
  - gem install jekyll-paginate
  - gem install jekyll-seo-tag
  - gem install jekyll-sitemap

# test:
#   stage: test
#   script:
#   - bundle exec jekyll build -d test
#   artifacts:
#     paths:
#     - test
#   except:
#   - master

pages:
  stage: deploy
  script:
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
